Repository bonitasoft/bonita-web-pages, pull requests merged in 2019-03, with the labels that each got.

#118 Initializing the bonita Portal layout in web pages
  settings.gradle
  uid-pages/layout-bonita/build.gradle
  uid-pages/layout-bonita/cypress.json
  uid-pages/layout-bonita/cypress/plugins/index.js
  uid-pages/layout-bonita/cypress/support/commands.js
  uid-pages/layout-bonita/cypress/support/defaults.js
  uid-pages/layout-bonita/cypress/support/index.js
  uid-pages/layout-bonita/src/LayoutBonitaV1.json
  uid-pages/layout-bonita/src/assets/css/layout.css
  uid-pages/layout-bonita/src/assets/js/layout.js
  uid-pages/layout-bonita/src/assets/json/localization.json
  uid-pages/layout-bonita/src/resources/page.properties
  uid-pages/layout-bonita/step_definitions/layoutBonita.js
  uid-pages/layout-bonita/test/mockServer/app1.json
  uid-pages/layout-bonita/test/mockServer/pageList.json
  uid-pages/layout-bonita/test/mockServer/ref.json
  uid-pages/layout-bonita/test/specs/layoutBonita.feature
Labels: Feedbacks integrated :fuelpump:, Review done

#119 feat(bonita-portal-layout) Adding header to the bonita portal
  settings.gradle
  uid-pages/layout-bonita/build.gradle
  uid-pages/layout-bonita/src/LayoutBonitaV1.json
  uid-pages/layout-bonita/src/assets/css/layout.css
  uid-pages/layout-bonita/step_definitions/layoutBonita.js
  uid-pages/layout-bonita/test/mockServer/json/app1.json
  uid-pages/layout-bonita/test/mockServer/json/pageList.json
  uid-pages/layout-bonita/test/mockServer/json/ref.json
  uid-pages/layout-bonita/test/mockServer/json/unusedId.json
  uid-pages/layout-bonita/test/mockServer/json/userFull.json
  uid-pages/layout-bonita/test/mockServer/json/userNoFirstname.json
  uid-pages/layout-bonita/test/mockServer/json/userNoLastname.json
  uid-pages/layout-bonita/test/specs/layoutBonita.feature
  widgets/customBonitaLayoutMenu/build.gradle
  widgets/customBonitaLayoutMenu/src/assets/css/style.css
  widgets/customBonitaLayoutMenu/src/assets/js/config-html5.js
  widgets/customBonitaLayoutMenu/src/assets/js/ui-bootstrap-tpls-0.13.0.min.js
  widgets/customBonitaLayoutMenu/src/customLayoutMenuBonitaV1.json
Labels: 👀 Review needed

#125 fix(case overview) fix Wrong business data retrieved
  uid-pages/form-case-overview/src/assets/css/style.css
  uid-pages/form-case-overview/src/caseoverview.json
Labels: Review done

#127 Making page names bigger
  widgets/customBonitaLayoutMenu/src/assets/css/style.css
Labels: Review done

#130 feat(layout) Manage default user icon
  build.gradle
  uid-pages/layout-bonita/src/LayoutBonitaV1.json
  uid-pages/layout-bonita/src/assets/css/layout.css
  uid-pages/layout-bonita/step_definitions/layoutBonita.js
  uid-pages/layout-bonita/test/mockServer/json/userDefaultImage.json
  uid-pages/layout-bonita/test/specs/layoutBonitaDesktop.feature
  uid-pages/layout-bonita/test/specs/layoutBonitaMobile.feature
  widgets/customBonitaLayoutMenu/src/customLayoutMenuBonitaV1.json
Labels: Review done

#129 feat(caseOverview) group by documents name
  .gitignore
  build.gradle
  uid-pages/form-case-overview/src/assets/css/style.css
  uid-pages/form-case-overview/src/assets/js/filters.js
  uid-pages/form-case-overview/src/assets/js/moment.min.js
  uid-pages/form-case-overview/src/assets/js/ui-bootstrap-tpls-0.13.0.min.js
  uid-pages/form-case-overview/src/caseoverview.json
  uid-pages/layout-living-application/src/LivingApplicationLayoutPageV5.json
  widgets/timelineWidget/src/timelineWidget.js
  widgets/timelineWidget/src/timelineWidget.json
Labels: Review done
