Repository bonitasoft/bonita-web-pages, pull requests merged in 2019-12, with the labels that each got.

#240 chore(template) Add default containers to the template
  templates/templatePage/%template-page-name%/src/%TemplatePageId%V1.json
Labels: 👀 Review needed

#251 chore(refactor) reorganize variables
  uid-pages/page-resources-list/src/ResourcesListBonitaV1.json
Labels: Review done

#252 feat(resource list) Adding localization keys
  uid-pages/page-resources-list/src/ResourcesListBonitaV1.json
  uid-pages/page-resources-list/src/assets/css/style.css
  uid-pages/page-resources-list/src/assets/json/localization.json
Labels: 👀 Review needed

#255 feat(user list page) Initialize user list page
  settings.gradle
  uid-pages/page-user-list/build.gradle
  uid-pages/page-user-list/cypress.json
  uid-pages/page-user-list/cypress/plugins/index.js
  uid-pages/page-user-list/cypress/support/commands.js
  uid-pages/page-user-list/cypress/support/defaults.js
  uid-pages/page-user-list/cypress/support/index.js
  uid-pages/page-user-list/src/UserListBonitaV1.json
  uid-pages/page-user-list/src/assets/css/style.css
  uid-pages/page-user-list/src/assets/json/localization.json
  uid-pages/page-user-list/src/resources/page.properties
  uid-pages/page-user-list/step_definitions/userList.js
  uid-pages/page-user-list/test/mockServer/json/emptyResult.json
  uid-pages/page-user-list/test/mockServer/json/users10.json
  uid-pages/page-user-list/test/mockServer/json/users20.json
  uid-pages/page-user-list/test/mockServer/json/users5.json
  uid-pages/page-user-list/test/specs/userList.feature
Labels: 👀 Review needed

#260 feat(user list) create user modal
  uid-pages/page-user-list/src/UserListBonitaV1.json
  uid-pages/page-user-list/step_definitions/userList.js
  uid-pages/page-user-list/test/mockServer/json/userAlreadyExists.json
  uid-pages/page-user-list/test/specs/changeStatusModal.feature
  uid-pages/page-user-list/test/specs/createUserModal.feature
Labels: Mob programmed
