Repository bonitasoft/bonita-web-pages, pull requests merged in 2019-11, with the labels that each got.

#223 add version after process name in the process filter
  uid-pages/page-user-case-list/src/assets/css/style.css
  uid-pages/page-user-case-list/src/assets/json/localization.json
  uid-pages/page-user-case-list/src/caselistBonitaV1.json
  uid-pages/page-user-case-list/test/mockServer/json/processes.json
  uid-pages/page-user-case-list/test/specs/userCaseListDesktop.feature
Labels: 👀 Review needed

#224 chore(CI): add 'release-*' in the list of base branches
  Jenkinsfile
Labels: ✔️Ready to merge

#225 fix(case overview) Display information instead of error when case not available
  uid-pages/form-case-overview/src/assets/json/localization.json
  uid-pages/form-case-overview/src/caseoverview.json
  uid-pages/form-case-overview/step_definitions/formCaseOverview.js
  uid-pages/form-case-overview/test/specs/formCaseOverview.feature
Labels: ✔️Ready to merge

#215 feat(guest user) add login button when logged in as guest
  uid-pages/layout-bonita/src/LayoutBonitaV4.json
  uid-pages/layout-bonita/src/assets/css/layout.css
  uid-pages/layout-bonita/src/assets/css/style.css
  uid-pages/layout-bonita/src/assets/json/localization.json
  uid-pages/layout-bonita/src/resources/page.properties
  uid-pages/layout-bonita/step_definitions/layoutBonita.js
  uid-pages/layout-bonita/test/mockServer/json/session.json
  uid-pages/layout-bonita/test/mockServer/json/sessionAsGuest.json
  uid-pages/layout-bonita/test/mockServer/json/sessionWithSSO.json
  uid-pages/layout-bonita/test/specs/layoutHeaderDesktop.feature
  uid-pages/layout-bonita/test/specs/layoutHeaderMobile.feature
  widgets/customBonitaLayoutMenu/src/assets/css/style.css
  widgets/customBonitaLayoutMenu/src/customLayoutMenuBonitaV3.ctrl.js
  widgets/customBonitaLayoutMenu/src/customLayoutMenuBonitaV3.json
  widgets/customBonitaLayoutMenu/src/customLayoutMenuBonitaV3.tpl.html
Labels: 👀 Review needed

#226 fix(bonita layout) Use standalone icon instead of the library
  uid-pages/layout-bonita/src/LayoutBonitaV4.json
  uid-pages/layout-bonita/src/assets/css/user-circle.css
  uid-pages/layout-bonita/src/assets/img/fa-solid-900.woff
  uid-pages/layout-bonita/src/assets/img/fa-solid-900.woff2
Labels: 👀 Review needed

#228 User case list sort by case ID
  uid-pages/page-user-case-list/src/assets/json/localization.json
  uid-pages/page-user-case-list/src/caselistBonitaV1.json
  uid-pages/page-user-case-list/step_definitions/user-case-list.js
  uid-pages/page-user-case-list/test/mockServer/json/archivedCasesSortedByProcessNameAsc.json
  uid-pages/page-user-case-list/test/mockServer/json/archivedCasesSortedByProcessNameDesc.json
  uid-pages/page-user-case-list/test/mockServer/json/archivedCasesSortedByStartDateNew.json
  uid-pages/page-user-case-list/test/mockServer/json/openCasesSortedByProcessNameAsc.json
  uid-pages/page-user-case-list/test/mockServer/json/openCasesSortedByProcessNameDesc.json
  uid-pages/page-user-case-list/test/mockServer/json/openCasesSortedByStartDateNew.json
  uid-pages/page-user-case-list/test/specs/userCaseListDesktop.feature
Labels: Review done

#230 chore(build gradle) Updating to the latest version of UID
  build.gradle
Labels: 👀 Review needed

#232 feat (case list) add translations
  uid-pages/page-user-case-list/src/assets/json/localization.json
Labels: 👀 Review needed

#235 Case list additional translation
  uid-pages/page-user-case-list/src/assets/json/localization.json
Labels: 👀 Review needed

#236 feat(Guest User) Guest User should support the use of SSO
  uid-pages/layout-bonita/src/LayoutBonitaV4.json
  uid-pages/layout-bonita/step_definitions/layoutBonita.js
  uid-pages/layout-bonita/test/mockServer/json/sessionAsGuestWithSSO.json
  uid-pages/layout-bonita/test/specs/layoutHeaderDesktop.feature
Labels: Review done

#238 feat(artifact templates) Add artifact templates to speed up creation
  templates/README.md
  templates/templatePage/%template-page-name%/build.gradle
  templates/templatePage/%template-page-name%/cypress.json
  templates/templatePage/%template-page-name%/cypress/plugins/index.js
  templates/templatePage/%template-page-name%/cypress/support/commands.js
  templates/templatePage/%template-page-name%/cypress/support/defaults.js
  templates/templatePage/%template-page-name%/cypress/support/index.js
  templates/templatePage/%template-page-name%/src/%TemplatePageId%V1.json
  templates/templatePage/%template-page-name%/src/resources/page.properties
  templates/templatePage/%template-page-name%/step_definitions/%templatePageId%.js
  templates/templatePage/%template-page-name%/test/mockServer/json/%apiCallResponseMock%.json
  templates/templatePage/%template-page-name%/test/specs/%templatePageId%Desktop.feature
  templates/templatePage/%template-page-name%/test/specs/%templatePageId%Mobile.feature
  templates/templateWidget/%templateWidgetName%/build.gradle
  templates/templateWidget/%templateWidgetName%/src/%templateWidgetId%V1.ctrl.js
  templates/templateWidget/%templateWidgetName%/src/%templateWidgetId%V1.json
  templates/templateWidget/%templateWidgetName%/src/%templateWidgetId%V1.tpl.html
Labels: 👀 Review needed

#233 fix (process list) responsive process list as per different screen sizes
  page-process-list/src/pages/Main/components/Filters.css
  page-process-list/src/pages/Main/components/Filters.js
  page-process-list/src/pages/Main/components/List.css
  page-process-list/src/pages/Main/components/List.js
  page-user-list/package-lock.json
Labels: 7.10.1

#237 feat(install export page) Add spinner when installing organization
  uid-pages/page-install-export-organization/src/assets/css/style.css
  uid-pages/page-install-export-organization/src/assets/json/localization.json
  uid-pages/page-install-export-organization/src/installExportOrganizationBonita.json
Labels: 7.11, 👀 Review needed
