Repository bonitasoft/bonita-web-pages, pull requests merged in 2020-11, with the labels that each got.

#435 feat(profile and task details): Add check for unavailable features
  uid-pages/page-admin-profile-list/src/adminProfileListBonitaV1.json
  uid-pages/page-admin-profile-list/step_definitions/adminProfileList.js
  uid-pages/page-admin-profile-list/test/mockServer/json/featureList.json
  uid-pages/page-admin-profile-list/test/specs/adminProfileList.feature
  uid-pages/page-admin-task-details/src/adminTaskDetailsBonitaV1.json
  uid-pages/page-admin-task-details/step_definitions/adminFailedTaskDetails.js
  uid-pages/page-admin-task-details/step_definitions/adminPendingTaskDetails.js
  uid-pages/page-admin-task-details/test/mockServer/json/featureList.json
  uid-pages/page-admin-task-details/test/specs/adminFailedTaskDetails.feature
  uid-pages/page-admin-task-details/test/specs/adminPendingTaskDetails.feature
Labels: Review done, ✔️Ready to merge

#438 feat (admin task list page): Implement refresh list button
  uid-pages/page-admin-task-list/src/adminTaskListBonitaV1.json
  uid-pages/page-admin-task-list/src/assets/json/localization.json
  uid-pages/page-admin-task-list/step_definitions/adminDoneTasksList.js
  uid-pages/page-admin-task-list/step_definitions/adminFailedFlowNodeslist.js
  uid-pages/page-admin-task-list/test/specs/adminDoneTasksListDesktop.feature
  uid-pages/page-admin-task-list/test/specs/adminFailedFlowNodesListDesktop.feature
  uid-pages/page-admin-task-list/test/specs/adminPendingTasksListDesktop.feature
Labels: Review done

#441 fix(pages): Standardize sort by options
  uid-pages/page-admin-resource-list/src/adminResourceListBonitaV1.json
  uid-pages/page-admin-resource-list/src/assets/json/localization.json
  uid-pages/page-admin-resource-list/step_definitions/resourcesList.js
  uid-pages/page-admin-resource-list/test/specs/resourcesList.feature
  uid-pages/page-user-case-list/src/UserCaseListBonitaV3.json
  uid-pages/page-user-case-list/src/assets/json/localization.json
  uid-pages/page-user-case-list/step_definitions/user-case-list.js
  uid-pages/page-user-case-list/test/specs/userCaseListDesktop.feature
Labels: Review done

#443 feat(details pages): Add missing id information
  uid-pages/form-case-overview/step_definitions/formCaseOverview.js
  uid-pages/form-case-overview/test/specs/formCaseOverview.feature
  uid-pages/page-admin-case-details/src/adminCaseDetailsBonitaV2.json
  uid-pages/page-admin-case-details/src/assets/json/localization.json
  uid-pages/page-admin-case-details/step_definitions/adminCaseDetails.js
  uid-pages/page-admin-case-details/test/specs/adminCaseDetails.feature
  uid-pages/page-admin-task-details/src/adminTaskDetailsBonitaV1.json
  uid-pages/page-admin-task-details/src/assets/json/localization.json
  uid-pages/page-admin-task-details/step_definitions/adminFailedTaskDetails.js
  uid-pages/page-admin-task-details/test/specs/adminDoneTaskDetails.feature
  uid-pages/page-admin-task-details/test/specs/adminFailedTaskDetails.feature
  uid-pages/page-user-case-details/src/UserCaseDetailsBonitaV1.json
  uid-pages/page-user-case-details/src/assets/json/localization.json
  uid-pages/page-user-case-details/step_definitions/userCaseDetails.js
  uid-pages/page-user-case-details/test/specs/userCaseDetails.feature
Labels: Review done

#444 Feat (user case list): access user case details from case list by case
  uid-pages/page-user-case-list/src/UserCaseListBonitaV3.json
  uid-pages/page-user-case-list/src/assets/css/style.css
  uid-pages/page-user-case-list/src/assets/json/localization.json
  uid-pages/page-user-case-list/step_definitions/user-case-list.js
  uid-pages/page-user-case-list/test/specs/userCaseListDesktop.feature
Labels: Review done

#449 Change delete button color to primary
  uid-pages/page-admin-resource-list/src/adminResourceListBonitaV1.json
  uid-pages/page-admin-role-list/src/adminRoleListBonitaV1.json
Labels: 👀 Review needed

#450 fix(layout) language selection with locale in URL
  uid-pages/layout-bonita/src/LayoutBonitaV6.json
  uid-pages/layout-bonita/step_definitions/layoutBonita.js
  uid-pages/layout-bonita/test/specs/layoutSessionModalDesktop.feature
Labels: Feedbacks integrated :fuelpump:, Review done

#453 Fix (orphan pages): Add orphan page information in the json and page.properties
  uid-pages/page-admin-case-details/src/adminCaseDetailsBonitaV2.json
  uid-pages/page-admin-case-details/src/resources/page.properties
  uid-pages/page-admin-task-details/src/adminTaskDetailsBonitaV1.json
  uid-pages/page-admin-task-details/src/resources/page.properties
  uid-pages/page-user-case-details/src/UserCaseDetailsBonitaV1.json
  uid-pages/page-user-case-details/src/resources/page.properties
Labels: 👀 Review needed

#451 Create user confirmation message
  uid-pages/page-admin-user-list/src/adminUserListBonitaV1.json
  uid-pages/page-admin-user-list/src/assets/json/localization.json
  uid-pages/page-admin-user-list/step_definitions/userList.js
  uid-pages/page-admin-user-list/test/specs/changeStatusModal.feature
  uid-pages/page-admin-user-list/test/specs/createUserModal.feature
Labels: Review done, ✔️Ready to merge

#452 fix(admin roles): Avoid disabling search when there is something in it
  uid-pages/page-admin-group-list/src/adminGroupListBonitaV1.json
  uid-pages/page-admin-group-list/src/assets/json/localization.json
  uid-pages/page-admin-group-list/step_definitions/adminGroups.js
  uid-pages/page-admin-group-list/test/specs/adminGroups.feature
  uid-pages/page-admin-role-list/src/adminRoleListBonitaV1.json
  uid-pages/page-admin-role-list/src/assets/json/localization.json
  uid-pages/page-admin-role-list/step_definitions/adminRoles.js
  uid-pages/page-admin-role-list/test/specs/adminRoles.feature
Labels: Feedbacks integrated :fuelpump:, Review done

#454 Fix (wrapped pages): Add wrapped page description in page.properties
  portaljs-pages/page-admin-application-details/resources/page.properties
  portaljs-pages/page-admin-application-list/resources/page.properties
  portaljs-pages/page-admin-bdm/resources/page.properties
  portaljs-pages/page-admin-case-list/resources/page.properties
  portaljs-pages/page-admin-case-visu/resources/page.properties
  portaljs-pages/page-admin-license/resources/page.properties
  portaljs-pages/page-admin-monitoring/resources/page.properties
  portaljs-pages/page-admin-process-details/resources/page.properties
  portaljs-pages/page-admin-process-visu/resources/page.properties
  portaljs-pages/page-admin-user-details/resources/page.properties
Labels: Review done

#463 Fix (admin groups list page): Modify the message when there is no result found
  uid-pages/page-admin-group-list/src/adminGroupListBonitaV1.json
  uid-pages/page-admin-group-list/src/assets/json/localization.json
  uid-pages/page-admin-group-list/step_definitions/adminGroups.js
Labels: Review done

#456 Fix (admin task details) disable fields in do for modal
  uid-pages/page-admin-task-details/src/adminTaskDetailsBonitaV1.json
  uid-pages/page-admin-task-details/step_definitions/adminPendingTaskDetails.js
  uid-pages/page-admin-task-details/test/specs/adminPendingTaskDetails.feature
Labels: Review done

#464 Fix (admin case details) Implement load more process variables button
  uid-pages/page-admin-case-details/src/adminCaseDetailsBonitaV2.json
  uid-pages/page-admin-case-details/src/assets/css/style.css
  uid-pages/page-admin-case-details/src/assets/json/localization.json
  uid-pages/page-admin-case-details/step_definitions/adminCaseDetails.js
  uid-pages/page-admin-case-details/test/mockServer/json/processVariables10.json
  uid-pages/page-admin-case-details/test/mockServer/json/processVariables20.json
  uid-pages/page-admin-case-details/test/specs/adminCaseDetails.feature
Labels: 👀 Review needed
