Repository bonitasoft/bonita-web-pages, pull requests merged in 2020-10, with the labels that each got.

#404 fix (admin roles page): Change the description inputs into textareas
  uid-pages/page-admin-roles/src/AdminRolesBonitaV1.json
  uid-pages/page-admin-roles/step_definitions/adminRoles.js
Labels: 👀 Review needed

#405 fix(layout) avoid redirecting to bonita portal when submitting a form in an app
  uid-pages/layout-bonita/src/LayoutBonitaV6.json
  uid-pages/layout-bonita/src/assets/css/style.css
  uid-pages/layout-bonita/src/assets/js/layout.js
  widgets/customBonitaLayoutMenu/src/customLayoutMenuBonitaV3.json
  widgets/customLivingApplicationIFrame/src/customLivingApplicationIFrameV4.json
Labels: 👀 Review needed

#417 chore(all pages): Update cypress page configurations
  uid-pages/form-case-overview/cypress.json
  uid-pages/layout-bonita/cypress.json
  uid-pages/layout-living-application/cypress.json
  uid-pages/page-admin-case-details/cypress.json
  uid-pages/page-admin-group-list/cypress.json
  uid-pages/page-admin-group-list/step_definitions/adminGroups.js
  uid-pages/page-admin-install-export-organization/cypress.json
  uid-pages/page-admin-process-list/cypress.json
  uid-pages/page-admin-resource-list/cypress.json
  uid-pages/page-admin-role-list/cypress.json
  uid-pages/page-admin-role-list/step_definitions/adminRoles.js
  uid-pages/page-admin-task-details/cypress.json
  uid-pages/page-admin-task-details/step_definitions/adminPendingTaskDetails.js
  uid-pages/page-admin-task-list/cypress.json
  uid-pages/page-admin-user-list/cypress.json
  uid-pages/page-tenant-status/cypress.json
  uid-pages/page-user-case-details/cypress.json
  uid-pages/page-user-case-list/cypress.json
Labels: Review done

#420 chore(tests): upgrade cypress version
  uid-pages/form-case-overview/cypress.json
  uid-pages/layout-bonita/cypress.json
  uid-pages/layout-living-application/cypress.json
  uid-pages/package.json
  uid-pages/page-admin-case-details/cypress.json
  uid-pages/page-admin-group-list/cypress.json
  uid-pages/page-admin-install-export-organization/cypress.json
  uid-pages/page-admin-process-list/cypress.json
  uid-pages/page-admin-profiles/cypress.json
  uid-pages/page-admin-profiles/step_definitions/adminProfiles.js
  uid-pages/page-admin-resource-list/cypress.json
  uid-pages/page-admin-role-list/cypress.json
  uid-pages/page-admin-task-details/cypress.json
  uid-pages/page-admin-user-list/cypress.json
  uid-pages/page-tenant-status/cypress.json
  uid-pages/page-user-case-details/cypress.json
  uid-pages/page-user-case-list/cypress.json
Labels: Review done

#423 chore(all pages): Increase number of pages kept in memory
  uid-pages/form-case-overview/cypress.json
  uid-pages/layout-bonita/cypress.json
  uid-pages/layout-living-application/cypress.json
  uid-pages/page-admin-case-details/cypress.json
  uid-pages/page-admin-group-list/cypress.json
  uid-pages/page-admin-install-export-organization/cypress.json
  uid-pages/page-admin-process-list/cypress.json
  uid-pages/page-admin-resource-list/cypress.json
  uid-pages/page-admin-role-list/cypress.json
  uid-pages/page-admin-task-details/cypress.json
  uid-pages/page-admin-task-list/cypress.json
  uid-pages/page-admin-user-list/cypress.json
  uid-pages/page-tenant-status/cypress.json
  uid-pages/page-user-case-details/cypress.json
  uid-pages/page-user-case-list/cypress.json
Labels: Review done

#424 chore(all pages): Migrate all the pages to 2.0 UID model version
  uid-pages/form-case-overview/src/assets/css/style.css
  uid-pages/form-case-overview/src/caseoverview.json
  uid-pages/layout-living-application/src/LivingApplicationLayoutPageV5.json
  uid-pages/page-admin-case-details/src/adminCaseDetailsBonitaV1.json
  uid-pages/page-admin-case-details/src/assets/css/style.css
  uid-pages/page-admin-install-export-organization/src/adminInstallExportOrganizationBonitaV1.json
  uid-pages/page-admin-install-export-organization/src/assets/css/style.css
  uid-pages/page-admin-process-list/src/adminProcessListBonitaV1.json
  uid-pages/page-admin-process-list/src/assets/css/style.css
  uid-pages/page-admin-resource-list/src/adminResourceListBonitaV1.json
  uid-pages/page-admin-resource-list/src/assets/css/style.css
  uid-pages/page-admin-task-list/src/adminTaskListBonitaV1.json
  uid-pages/page-admin-task-list/src/assets/css/style.css
  uid-pages/page-application-home/src/ApplicationHomeBonita.json
  uid-pages/page-application-home/src/assets/css/style.css
  uid-pages/page-tenant-status/src/assets/css/style.css
  uid-pages/page-tenant-status/src/tenantStatusBonitaV1.json
  uid-pages/page-user-case-details/src/UserCaseDetailsBonitaV1.json
  uid-pages/page-user-case-details/src/assets/css/style.css
  uid-pages/page-user-case-list/src/UserCaseListBonitaV3.json
  uid-pages/page-user-case-list/src/assets/css/style.css
  widgets/customLivingApplicationMenu/src/customLivingApplicationMenuV4.json
  widgets/timelineWidget/src/timelineWidget.json
Labels: 👀 Review needed

#427 fix(layout) logout mechanism not working properly
  uid-pages/layout-bonita/src/LayoutBonitaV6.json
Labels: Review done, ✔️Ready to merge

#432 fix (UID pages) load more button limitation
  uid-pages/page-admin-group-list/src/adminGroupListBonitaV1.json
  uid-pages/page-admin-group-list/test/specs/adminGroups.feature
  uid-pages/page-admin-process-list/src/adminProcessListBonitaV1.json
  uid-pages/page-admin-process-list/test/specs/adminDisabledProcessList.feature
  uid-pages/page-admin-process-list/test/specs/adminEnabledProcessList.feature
  uid-pages/page-admin-resource-list/src/adminResourceListBonitaV1.json
  uid-pages/page-admin-resource-list/test/specs/resourcesList.feature
  uid-pages/page-admin-role-list/src/adminRoleListBonitaV1.json
  uid-pages/page-admin-role-list/test/specs/adminRoles.feature
  uid-pages/page-admin-task-list/src/adminTaskListBonitaV1.json
  uid-pages/page-admin-task-list/test/specs/adminDoneTasksListDesktop.feature
  uid-pages/page-admin-task-list/test/specs/adminFailedFlowNodesListDesktop.feature
  uid-pages/page-admin-task-list/test/specs/adminPendingTasksListDesktop.feature
  uid-pages/page-admin-user-list/src/adminUserListBonitaV1.json
  uid-pages/page-admin-user-list/test/specs/userList.feature
  uid-pages/page-user-case-list/src/UserCaseListBonitaV3.json
  uid-pages/page-user-case-list/test/specs/userCaseListDesktop.feature
Labels: 👀 Review needed

#426 feat(task details): Use the new replay task API
  uid-pages/page-admin-task-details/src/adminTaskDetailsBonitaV1.json
  uid-pages/page-admin-task-details/src/assets/json/localization.json
  uid-pages/page-admin-task-details/step_definitions/adminDoneTaskDetails.js
  uid-pages/page-admin-task-details/step_definitions/adminFailedTaskDetails.js
  uid-pages/page-admin-task-details/step_definitions/adminPendingTaskDetails.js
  uid-pages/page-admin-task-details/test/mockServer/json/executingTaskDetails.json
  uid-pages/page-admin-task-details/test/mockServer/json/initializingTaskDetails.json
  uid-pages/page-admin-task-details/test/mockServer/json/threeFailedConnectors.json
  uid-pages/page-admin-task-details/test/specs/adminFailedTaskDetails.feature
Labels: Review done, ✔️Ready to merge

#434 fix (admin groups page): Fix the load more button limitation
  uid-pages/page-admin-group-list/src/adminGroupListBonitaV1.json
  uid-pages/page-admin-group-list/test/specs/adminGroups.feature
  uid-pages/page-admin-process-list/src/adminProcessListBonitaV1.json
  uid-pages/page-admin-process-list/test/specs/adminDisabledProcessList.feature
  uid-pages/page-admin-process-list/test/specs/adminEnabledProcessList.feature
  uid-pages/page-admin-resource-list/src/adminResourceListBonitaV1.json
  uid-pages/page-admin-resource-list/test/specs/resourcesList.feature
  uid-pages/page-admin-role-list/src/adminRoleListBonitaV1.json
  uid-pages/page-admin-role-list/test/specs/adminRoles.feature
  uid-pages/page-admin-task-list/src/adminTaskListBonitaV1.json
  uid-pages/page-admin-task-list/test/specs/adminDoneTasksListDesktop.feature
  uid-pages/page-admin-task-list/test/specs/adminFailedFlowNodesListDesktop.feature
  uid-pages/page-admin-task-list/test/specs/adminPendingTasksListDesktop.feature
  uid-pages/page-admin-user-list/src/adminUserListBonitaV1.json
  uid-pages/page-admin-user-list/test/specs/userList.feature
  uid-pages/page-user-case-list/src/UserCaseListBonitaV3.json
  uid-pages/page-user-case-list/test/specs/userCaseListDesktop.feature
Labels: Review done, ✔️Ready to merge
