Repository bonitasoft/bonita-web-pages, pull requests merged in 2020-06, with the labels that each got.

#340 Correcting grammar mistakes in uid-pages README
  README.md
  uid-pages/README.md
Labels: 👀 Review needed

#337 Feat (admin task details) implement General, Connectors, and Comment sections
  uid-pages/page-admin-task-details/src/AdminTaskDetailsBonitaV1.json
  uid-pages/page-admin-task-details/src/assets/css/style.css
  uid-pages/page-admin-task-details/step_definitions/adminDoneTaskDetails.js
  uid-pages/page-admin-task-details/step_definitions/adminFailedTaskDetails.js
  uid-pages/page-admin-task-details/step_definitions/adminPendingTaskDetails.js
  uid-pages/page-admin-task-details/step_definitions/adminTaskDetails.js
  uid-pages/page-admin-task-details/test/mockServer/json/comments.json
  uid-pages/page-admin-task-details/test/mockServer/json/doneTaskDetails.json
  uid-pages/page-admin-task-details/test/mockServer/json/emptyResult.json
  uid-pages/page-admin-task-details/test/mockServer/json/executedConnector.json
  uid-pages/page-admin-task-details/test/mockServer/json/failedConnector.json
  uid-pages/page-admin-task-details/test/mockServer/json/failedTaskDetails.json
  uid-pages/page-admin-task-details/test/mockServer/json/newComments.json
  uid-pages/page-admin-task-details/test/mockServer/json/pendingTaskDetails.json
  uid-pages/page-admin-task-details/test/mockServer/json/toBeExecutedConnector.json
  uid-pages/page-admin-task-details/test/specs/adminDoneTaskDetails.feature
  uid-pages/page-admin-task-details/test/specs/adminFailedTaskDetails.feature
  uid-pages/page-admin-task-details/test/specs/adminPendingTaskDetails.feature
  uid-pages/page-admin-task-details/test/specs/adminTaskDetails.feature
Labels: 👀 Review needed

#343 feat (admin task details) finalize and test failed connector modal
  uid-pages/page-admin-task-details/src/AdminTaskDetailsBonitaV1.json
  uid-pages/page-admin-task-details/src/assets/css/style.css
  uid-pages/page-admin-task-details/step_definitions/adminFailedTaskDetails.js
  uid-pages/page-admin-task-details/test/mockServer/json/failedConnector.json
  uid-pages/page-admin-task-details/test/mockServer/json/failureConnector.json
  uid-pages/page-admin-task-details/test/specs/adminFailedTaskDetails.feature
Labels: 👀 Review needed

#344 fix (admin-task-details) fix pending task overdue icon
  uid-pages/page-admin-task-details/src/AdminTaskDetailsBonitaV1.json
Labels: Review done

#345 feat(admin case list) Passing filters to the iframe
  portaljs-pages/page-admin-case-list/src/index.html
Labels: Review done, ✔️Ready to merge
