Repository bonitasoft/bonita-web-pages, pull requests merged in 2020-03, with the labels that each got.

#306 feat (admin-process-list) wrap admin process details to admin process
  portaljs-pages/page-admin-process-details/build.gradle
  portaljs-pages/page-admin-process-details/package.json
  portaljs-pages/page-admin-process-details/resources/page.properties
  portaljs-pages/page-admin-process-details/src/index.html
  settings.gradle
  uid-pages/page-admin-process-list/src/AdminProcessListBonitaV1.json
Labels: 👀 Review needed

#312 feat (admin process list) change unresolved tooltip
  uid-pages/page-admin-process-list/src/AdminProcessListBonitaV1.json
  uid-pages/page-admin-process-list/src/assets/css/style.css
  uid-pages/page-admin-process-list/src/assets/json/localization.json
  uid-pages/page-admin-process-list/step_definitions/adminDisabledProcessList.js
  uid-pages/page-admin-process-list/step_definitions/adminEnabledProcessList.js
Labels: 👀 Review needed

#314 feat (admin process list) add guidance for unresolved process
  uid-pages/page-admin-process-list/src/AdminProcessListBonitaV1.json
  uid-pages/page-admin-process-list/src/assets/json/localization.json
  uid-pages/page-admin-process-list/step_definitions/adminDisabledProcessList.js
Labels: 👀 Review needed

#317 feat (admin task list) implement global caseId filter
  uid-pages/page-admin-task-list/src/AdminTaskListBonitaV1.json
  uid-pages/page-admin-task-list/src/assets/css/style.css
  uid-pages/page-admin-task-list/src/assets/json/localization.json
  uid-pages/page-admin-task-list/step_definitions/adminDoneTasksList.js
  uid-pages/page-admin-task-list/step_definitions/adminFailedFlowNodeslist.js
  uid-pages/page-admin-task-list/step_definitions/adminPendingTasksList.js
  uid-pages/page-admin-task-list/test/specs/adminDoneTasksListDesktop.feature
  uid-pages/page-admin-task-list/test/specs/adminFailedFlowNodesListDesktop.feature
  uid-pages/page-admin-task-list/test/specs/adminPendingTasksListDesktop.feature
Labels: 👀 Review needed

#325 feat(process visualization) Wrap process visu page
  portaljs-pages/page-admin-process-visu/build.gradle
  portaljs-pages/page-admin-process-visu/package.json
  portaljs-pages/page-admin-process-visu/resources/page.properties
  portaljs-pages/page-admin-process-visu/src/index.html
  settings.gradle
Labels: Review done, ✔️Ready to merge

#326 feat(case visualization) Wrap case visu page
  portaljs-pages/page-admin-case-visu/build.gradle
  portaljs-pages/page-admin-case-visu/package.json
  portaljs-pages/page-admin-case-visu/resources/page.properties
  portaljs-pages/page-admin-case-visu/src/index.html
  settings.gradle
Labels: Review done, ✔️Ready to merge

#328 feat(application tokens) Make tokens more consistent
  uid-pages/page-admin-process-list/src/AdminProcessListBonitaV1.json
  uid-pages/page-admin-process-list/step_definitions/adminDisabledProcessList.js
  uid-pages/page-admin-process-list/step_definitions/adminEnabledProcessList.js
  uid-pages/page-admin-task-list/src/AdminTaskListBonitaV1.json
  uid-pages/page-admin-task-list/step_definitions/adminDoneTasksList.js
  uid-pages/page-admin-task-list/step_definitions/adminFailedFlowNodeslist.js
  uid-pages/page-user-case-details/src/UserCaseDetailsBonitaV1.json
  uid-pages/page-user-case-details/step_definitions/userCaseDetails.js
  uid-pages/page-user-list/src/UserListBonitaV1.json
Labels: Review done

#329 fix (wrapped pages) remove version from page name
  portaljs-pages/page-admin-case-list/resources/page.properties
  portaljs-pages/page-admin-case-visu/resources/page.properties
  portaljs-pages/page-admin-process-details/resources/page.properties
  portaljs-pages/page-admin-process-visu/resources/page.properties
  portaljs-pages/page-user-details/resources/page.properties
Labels: 👀 Review needed
